# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline_salary

# Déclenche le workflow lors d'un push sur la branche main
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs du pipeline
jobs:
  # Job de test de l'API
  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test API
        run: |
          pytest -v

  # Job de déploiement sur AWS EC2
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf salarypredictiondocker
            git clone git@github.com:MarwenAouini/salarypredictiondocker.git
            cd salarypredictiondocker
            sudo docker-compose build
            sudo docker-compose up -d
            
  # Job de notification par e-mail
  notify:
    name: Notify
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify by Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.dunasys.com 
          # Server port, default 25: 
          server_port: 587 
          # Optional (recommended) mail server username:
          username: ${{ secrets.MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MAIL_PASSWORD }}
          # Required mail subject:
          subject: "Notification de déploiement"
          # Required recipients' addresses:
          to: ${{ secrets.RECI_ADDRESS}}
          # Required sender full name (address can be skipped):
          from: ${{ secrets.SEND_ADDRESS}}
          # Optional plain body:
          body: "Le déploiement de l'API xxx Prediction a été effectué avec succès."
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
