# This is a basic workflow to help you get started with Actions

name: CI_salary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf salarypredictiondocker
            git clone git@github.com:MarwenAouini/salarypredictiondocker.git
            cd salarypredictiondocker
            sudo docker-compose build
            sudo docker-compose up -d
# Job de notification par e-mail
  notify:
    name: Notify
    #needs: [jobs]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify by Email
        uses: danthe1st/email-filechange-notif-action@v1
        with:
          # The E-Mail address used to send the E-Mails
          senderEmail: "marwen.aou@gmail.com"
          # A file in the repository or HTTP address that contains file patterns with E-Mail addresses that should be notified on file changes
          mailingList: "marwen_aouini@hotmail.fr"
          # The subject of the E-Mails to send
          subjectLine: "Notification de déploiement"
          body: "Le déploiement de l'API Salary Prediction a été effectué avec succès."
          # The SMTP server used to send E-Mails
          smtpServer: smtp.gmail.com
          # The SMTP port used to send E-Mails
          smtpPort: 587 # optional, default is 587
          # The SMTP user name used to send E-Mails
          smtpUsername: ${{ secrets.GMAIL_USERNAME }}
          # The SMTP password used to send E-Mails
          smtpPassword: ${{ secrets.GMAIL_PASSWORD }}
          #Token used for cloning the repository
          #githubToken: # optional, default is ${{ github.token }}
