# This is a basic workflow to help you get started with Actions

name: CI_salary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf salarypredictiondocker
            git clone git@github.com:MarwenAouini/salarypredictiondocker.git
            cd salarypredictiondocker
            sudo docker-compose build
            sudo docker-compose up -d
  # Job de notification par e-mail
  notify:
    name: Notify
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify by Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.dunasys.com 
          # Server port, default 25: 
          server_port: 587 
          # Optional (recommended) mail server username:
          username: ${{ secrets.MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MAIL_PASSWORD }}
          # Required mail subject:
          subject: "Notification de déploiement"
          # Required recipients' addresses:
          to: "marwen.aou@gmail.com"
          # Required sender full name (address can be skipped):
          from: "marwen.aouini@dunasys.com"
          # Optional plain body:
          body: "Le déploiement de l'API xxx Prediction a été effectué avec succès."
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
